# These are supported funding model platforms

patreon: marshevEngi
open_collective: zcorp
# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://www.buymeacoffee.com/marshevEngi']
